# Simulated periodic request to your Render project so that the service doesn't stay idle
# Now pings every 30 minutes (UTC)
name: Half-hourly render ping

on:
  schedule:
    # Run every 15 minutes. Uses UTC cron syntax: minute hour day month weekday
    - cron: '*/15 * * * *'


jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Run cURL on Website
        run: curl -I https://aggroso-tha-backend.onrender.com/
